### ISSUE TITLE
Quarkus: Supersonic, Subatomic Java

### ISSUE THREAD

**Issue by hpehl** [dev-night/talks#47]
* **Speaker**: Harald Pehl (hpehl@redhat.com)
* **Duration**: 1h
* **Slides**: n/a yet
* **Description**: `Quarkus is a microservices Java stack bringing your favorite libs (Hibernate, vert.x, Camel, RESTEasy ...) to GraalVM and HotSpot with low memory usage and fast boot time. The talk gives an introduction to Quarkus and shows the techniques used behind the scenes. Examples and live coding show you how to use Quarkus starting from Maven archetype to OpenShift deployment.`

**Comment by niklas-heer** [comment]
Thank you @hpehl for you talk suggestions. 
This is a nice topic since Java is up until now underrepresented. :sweat_smile: 

You estimate an hour so we either could fill a whole evening with this topic or maybe we could add it to our special event in July for the Nürnberg Digital Festival.
The dates would be:
* 16th of July Nürnberg Digital Festival special (multiple talks)
* 13th of August (the whole evening)
 
Any preferences?

**Comment by hpehl** [comment]
13th of August would work for me. I could try to extend the hour and give some kind of workshop. Or we just have an open discussion.

**Comment by niklas-heer** [comment]
@hpehl of cause, that makes total sense :+1: 
Yes I think an open discussion would be nice. So let's make it official. 

Any ideas for the event title?

**Comment by hpehl** [comment]
Not sure, what about something like "Java weather forecast: cheerful to cloudy". This leads to the question whether the talk, abstract and slides should be in English or German?

**Comment by niklas-heer** [comment]
I really like your title :) We'll take that.
Regarding the German vs. English question: My suggestion would be to prepare everything in English including slides etc. and then ask at the presentation if there is anyone which does not speak German in the crowd. Because often we have people in the audience which do not speak German.
What do you think?

Also sorry for the late response!

**Comment by hpehl** [comment]
No worries ;-)
Ok let's do so. I'll prepare everything in English and then it's up to the audience.

**Comment by niklas-heer** [comment]
@hpehl that sounds great! Thank you very much!

**Comment by niklas-heer** [comment]
Hi @hpehl I just wanted to check if the 13th of August is still working out for you? :)

**Comment by hpehl** [comment]
Yes @niklas-heerm, 13th of August still works for me.

**Comment by niklas-heer** [comment]
@hpehl Perfect so see you in August. Thank you very much!

**Comment by niklas-heer** [comment]
It was a great talk thanks again @hpehl with this done I'll close this issue :slightly_smiling_face:
